[build]
  functions = "functions"

[[redirects]]
  from = "*"
  to = "https://8428394.hs-sites.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "Content-Type"
      Access-Control-Allow-Methods = "GET, POST, OPTIONS"